language: cpp

compiler:
  - gcc

os:
  - linux
  - osx

env:
  - TARGET="CLI"
  - TARGET="API"

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x scripts/*

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/install_deps_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/install_deps_osx.sh; fi

script:
  - if [ "$TARGET" = "CLI" ]; then ./scripts/test_cli.sh; fi
  - if [ "$TARGET" = "API" ]; then ./scripts/test_port.sh; fi
  - tree
