language: cpp

compiler:
  - gcc

os:
  - linux

env:
  - TARGET="CLI"
  - TARGET="API"

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
  - chmod +x cmake-3.14.2-Linux-x86_64.sh
  
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cmake-3.14.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license; fi
  
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x scripts/*

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/install_deps_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/install_deps_osx.sh; fi

script:
  - if [ "$TARGET" = "CLI" ]; then ./scripts/test_cli.sh; fi
  - if [ "$TARGET" = "API" ]; then ./scripts/test_port.sh; fi
  - tree
