language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install libboost-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-8
  - sudo apt-get install g++-8

script:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./run install
  - . ./run port
