language: cpp

compiler:
  - gcc

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
  - chmod +x cmake-3.14.2-Linux-x86_64.sh
  - ./cmake-3.14.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install libboost-dev
  - sudo apt-get install gcc-8
  - sudo apt-get install g++-8

script:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./run install
  - . ./run port
